#!/bin/bash

## You can read this like an install doc, or just run it with bash. Designed for Ubuntu.

# 1.0 Install the nodejs.

sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get -q update

# 1.1 Remove any lingering distro based nodejs packages.

sudo apt-get remove -y nodejs nodejs-dev npm

# 1.2 Install node.js from PPA

sudo apt-get install -y nodejs

# 2.0 Install Jade templating engine

sudo npm install -g jade

# 2.1 Install Stylus

sudo npm install -g stylus
